"""Current lecture alignment: preserve existing teaching, code and outputs."""
import re
from html import escape
from lib import detail


def extend(body, pid, content):
    """Insert without reparsing source: lab whitespace is immutable."""
    start = re.search(r'<details\b[^>]*\bid="'+re.escape(pid)+r'"[^>]*>', body)
    if not start:
        raise ValueError("Missing detail: "+pid)
    depth = 1
    for token in re.finditer(r'</?details\b[^>]*>', body[start.end():]):
        depth += -1 if token.group().startswith('</') else 1
        if depth == 0:
            end = start.end()+token.start()
            close = body.rfind('</div>', start.end(), end)
            return body[:close]+content+body[close:]
    raise ValueError("Unclosed detail: "+pid)


def augment(bodies):
    bodies['prologue'] += detail('w08-detail-lecture-roadmap', '非線性模型的共同框架與選擇依據', '\n<p>「對變數非線性」不代表「對係數非線性」。多項式、階梯與固定節點的樣條都先建立基底，再估計基底的係數。把同一組基底排成設計矩陣後，迴歸可沿用最小平方；分類可沿用 GLM。各方法的差別在於：曲線可以在哪裡彎曲、彎曲多少，以及如何控制複雜度。</p>\n<p>先問三件事：需要解讀單一變數的形狀嗎？兩端外推合理嗎？資料是否足以估計交互作用？多項式牽動整條曲線，樣條讓變化比較局部，局部迴歸在每個目標位置重新估計，GAM 則把多個一維效果加起來。選擇方法時，還要檢查曲線在新資料上的表現；次數、自由度、平滑參數與跨距應用保留資料或 CV 比較。</p>\n<p>講義連結的表格資料模型比較研究提醒我們：演算法的表現依資料型態、樣本數、調參預算而變。這裡先建立可解讀的非線性工具；樹與深度學習的比較不能直接用來判定 Wage 的最佳方法。對相同資料和切分比較預測誤差，再把邊界、可解讀性及計算需求一起考量，才能選出適合資料與任務的方法。</p>\n')
    bodies['poly'] = extend(bodies['poly'], 'w08-detail-poly-calculation', "\n<h3>同一條曲線，為什麼需要整個共變異數矩陣？</h3>\n<p>Wage 的四次年齡模型把 $b(x)=(1,x,x^2,x^3,x^4)^T$ 作為基底。在指定年齡 $x_0$，預測的平均薪資是 $b(x_0)^T\\hat\\beta$。係數估計通常彼此相關；把各係數標準誤分別乘上 $x_0$ 的冪次再相加，會漏掉共變異項，並不等於預測曲線的標準誤。</p>\n$$\\widehat{\\operatorname{Var}}\\{\\hat f(x_0)\\}=b(x_0)^T\\widehat{\\operatorname{Cov}}(\\hat\\beta)b(x_0).$$\n<p>在常態、等變異、獨立誤差及滿秩設計下，$\\widehat{\\operatorname{Cov}}(\\hat\\beta)=\\hat\\sigma^2(B^TB)^{-1}$，$\\hat\\sigma^2=RSS/(n-q)$，其中 $q$ 是含截距的係數個數。平均反應的區間用 $\\hat f(x_0)\\pm t_{n-q,1-\\alpha/2}s_f$；個別新薪資的預測區間則用 $\\sqrt{s_f^2+\\hat\\sigma^2}$，多出一個新觀測本身的誤差變異。講義中簡單線性迴歸的 $1/n$ 與槓桿公式是此矩陣式在兩欄基底下的特例，不能原封不動套到四次模型。</p>\n<p>Lab 的 <code>plot_wage_fit</code> 使用 <code>get_prediction</code> 計算平均擬合的標準誤，再畫 $\\hat f\\pm2s_f$。這是逐點近似區間：每個固定年齡各自有涵蓋率，沒有保證整條未知曲線同時位於帶內。<code>summary_frame</code> 的 <code>mean_ci_*</code> 和 <code>obs_ci_*</code> 分別回答平均與個別觀測的問題。</p>\n<h3>正交多項式、ANOVA 與交叉驗證</h3>\n<p>Lab 的 <code>poly('age', degree=4)</code> 用正交多項式改善數值條件；把相同次數的原始冪次改用另一組滿秩基底表示，不會改變張成的模型空間。因此擬合值相同，係數卻不同，不能把正交基底的第二欄係數讀成年齡平方的係數。新資料必須由訓練時已擬合的轉換器 <code>transform</code>，不能各自重新正交化。</p>\n<p><code>anova_lm</code> 比較 1–5 次的巢狀模型。由低次升至高次時，新增項的 RSS 降幅相對於殘差變異形成 F 統計量；只加一個係數時，該 F 等於相應 t 統計量的平方。它是在指定模型、誤差條件下檢定新增項，不是直接估計泛化誤差。CV 則在每折重新擬合基底和模型，再比較留出觀測的損失；以全資料的轉換器先處理各折，會把應由訓練折決定的資訊帶入驗證折。</p>\n")
    bodies['step'] = extend(bodies['step'], 'w08-detail-step-coding', '\n<h3>等寬與等人數切分，回答的是不同問題</h3>\n<p><code>pd.cut(age,4)</code> 把年齡範圍分成四個等寬區間；<code>pd.qcut(age,4)</code> 依分位數分成樣本數大致相近的四組。年齡重複值集中時，分位數邊界可能重複，因此不能只由「四組」推論實際得到四個可用區間。講義指定 35、50、65 的切點是依年齡意義分組，也不同於自動等寬或等人數切分。</p>\n<p>若保留所有組別的 indicator，就不另加截距：每組係數直接等於該組平均。若包含截距，便刪去一個組別欄位；截距是參考組平均，其他係數是相對參考組的差。兩種編碼可表示同一組分段常數，不能把「少一個欄位」理解為少估了一個組別。</p>\n<p>Lab 的四個年齡區段分別估計平均薪資。邊界左閉或右閉由切分函式設定決定，實作必須保留同一規則；預測新資料時也應沿用訓練資料的切點，而不是重新計算它的分位數。用年齡區段與年份交互作用時，模型可以讓各組有不同年份斜率；這是在加入可解讀的交互作用，並不會讓分段常數自動變得連續。</p>\n')
    bodies['natural'] = extend(bodies['natural'], 'w08-detail-natural-basis', "\n<h3>先數內部節點，再說自由度</h3>\n<p>講義使用的 $K$ 有兩種節點計數方式。一般三次樣條若有 $m$ 個<strong>內部</strong>節點，含截距的空間維度是 $m+4$。自然三次樣條加上兩端線性條件後，維度是 $m+2$。若改把左右邊界也算入節點總數，$K=m+2$，自然樣條的維度才寫成 $K$。這兩種說法描述相同空間，不能把 $K+4$ 和 $K$ 直接相減而忽略節點定義。</p>\n<p>每個內部節點允許曲率改變。把節點放在樣本分位數，可讓各區域都有觀測資料；等距節點在資料稀疏的尾端可能配置過多彈性。邊界外線性限制減少極端振盪，仍不能保證訓練範圍外的預測可靠；新年齡遠超過訓練範圍時仍沒有資料可以驗證延伸的斜率。</p>\n<h3>對照 Lab 的七欄與六欄</h3>\n<p>Lab 的 <code>BSpline(internal_knots=[25,40,60], intercept=True)</code> 產生七欄，正是三個內部節點加四個三次多項式自由度。<code>bs('age', internal_knots=[25,40,60])</code> 預設不包含截距基底，會保留六欄，再由 <code>ModelSpec</code> 加上整體截距。兩種總維度一致；不能再把完整七欄和常數欄一起送入模型，造成線性相依。</p>\n<p>Patsy 的 <code>bs</code> 與 <code>cr</code> 是建立設計矩陣的工具：<code>cr</code> 的自然邊界條件不等於懲罰平滑擬合。使用 <code>constraints='center'</code> 時還會吸收中心化限制，因此要一起檢查基底欄數、截距與秩，而非把函式引數 <code>df</code> 一律當成模型總自由度。預測新資料用 <code>build_design_matrices</code> 沿用原 <code>design_info</code>；重新呼叫建立基底可能改變節點。</p>\n<p>若要以 CV 選自由度，每折先從訓練年齡決定節點、擬合模型，再把同一轉換套到留出年齡。以每個候選自由度的折外誤差比較，最後在完整訓練資料建立選定模型。不要在測試資料上反覆挑選「看起來最平滑」的曲線。</p>\n")
    bodies['smooth'] = extend(bodies['smooth'], 'w08-detail-smoothing-computation', "\n<h3>懲罰不是刪掉節點，而是限制曲率</h3>\n<p>平滑樣條在每個相異訓練 $x$ 放節點，但以 $\\lambda\\int[g''(t)]^2dt$ 收縮彎曲部分。懲罰的零空間是直線：若 $g''=0$，曲率成本為零。因此 $\\lambda$ 很大時保留下來的是最佳線性趨勢，不是整條曲線縮至零。資料點重複時，應以相異位置或適當加權表示；不能無條件宣稱「$n$ 個節點、$n$ 個完全獨立參數」。</p>\n<p>固定 $\\lambda$ 時，$S_\\lambda$ 決定觀測如何互相影響，$\\operatorname{tr}(S_\\lambda)$ 是擬合反應對原反應的總敏感度。它常不是整數，也不等於矩陣 $B$ 的欄數。與固定自由度的迴歸樣條相比，平滑樣條主要選 $\\lambda$，而不是逐個挑節點。</p>\n<p>LOOCV 捷徑使用 $(y_i-\\hat g(x_i))/(1-S_{ii})$。分母大致補回該觀測對自己預測的影響；當 $S_{ii}$ 接近 1，留一誤差可能很大。此式要求相同線性平滑規則，不能把二元反應的 IRLS 權重、資料驅動選節點或已調過的 $\\lambda$ 當作固定，就以為不用重新擬合也能評估完整的模型選擇流程。</p>\n<h3>由曲率矩陣連到二元分類</h3>\n<p>二元模型改用 Bernoulli 對數概似。第 $t$ 步以目前 $p_i$ 建立 $W_{ii}=p_i(1-p_i)$ 與工作反應 $z_i=\\eta_i+(y_i-p_i)/W_{ii}$，再解 $(B^TWB+\\lambda\\Omega)\\beta_{new}=B^TWz$。每步都更新權重與工作反應；最後將線性分數轉成機率。$p$ 接近 0 或 1 時權重變小，也提醒我們檢查分離與數值穩定性。</p>\n<p>講義連結的 Bone Mineral Density notebook 是另一個平滑曲線例子；它用來展示相同的基底與懲罰框架，不取代本課 Wage 的資料與輸出。Lab 的 <code>pyGAM</code> 使用具有平滑懲罰的樣條項，與精確自然平滑樣條屬於相關但不同的參數化；不能因都叫 spline 就宣稱兩者結果必然相同。</p>\n")
    bodies['loess'] = extend(bodies['loess'], 'w08-detail-local-calculation', '\n<h3>同一份訓練資料，每個目標點重新給權重</h3>\n<p>先指定跨距 $s$，在目標 $x_0$ 選約 $sn$ 個最近鄰，再用最遠入選鄰居的距離作尺度 $h(x_0)$。距離越近權重越大，以 $\\sum_iw_i(x_0)[y_i-a-b(x_i-x_0)]^2$ 求局部直線。$x=x_0$ 的預測是截距 $a$；下一個目標點要重新選鄰居、權重和局部係數，而不是沿用上一條直線。</p>\n<p>局部常數只做加權平均，在邊界的鄰居只剩單側，容易有偏差；局部直線能修正部分邊界趨勢，但樣本稀疏或局部設計秩不足時仍不穩定。小跨距保留細節也增加變異，大跨距平均更多資料也可能抹去真實變化。跨距需在訓練資料內用驗證比較，不能只看曲線是否穿過每個點。</p>\n<p>Lab 使用 <code>statsmodels.nonparametric.lowess</code> 的 <code>frac</code> 控制鄰居比例。<code>it</code> 是殘差穩健化的額外迭代，會依殘差降低離群觀測權重；不是多項式的次數。Wage 圖中的局部擬合若要與手寫一次加權直線比較，必須同時對照排序、跨距與穩健化迭代的設定。</p>\n<p>講義延伸的變係數模型把「附近」改為時間附近：在每個目標時間內擬合薪資對其他變數的係數，得到 $\\beta_j(t)$。二維局部平面則用兩個變數共同定義鄰域。兩者都需要局部觀測資料支持；高維距離變得稀疏，解釋了為何不能直接把一維 LOWESS 無限制推廣到所有特徵。</p>\n')
    bodies['gam'] = extend(bodies['gam'], 'w08-detail-gam-lab', '\n<h3>Wage 模型中的三個成分各自代表什麼？</h3>\n<p>講義先使用 $wage=\\beta_0+f_1(year)+f_2(age)+f_3(education)+\\varepsilon$：年份和年齡是平滑項，教育是五個水準的組別效果。固定基底時，將各項的基底欄串接即可使用 OLS；需要懲罰時，則在相同目標中加入各平滑項的曲率成本。每個平滑項都需要可識別限制，例如訓練樣本上的平均效果為零，常數水準由截距承接。</p>\n<p>Lab 的 <code>LinearGAM(s(0)+s(1)+f(2))</code> 用欄位位置指出項：<code>s</code> 表示樣條平滑，<code>f</code> 表示類別項。欄位順序不是文字標籤，必須核對傳入矩陣中 year、age、education 的位置。各項曲線的縱軸是模型成分，不能直接當成未控制其他變數的平均薪資。</p>\n<p>講義比較自然樣條與平滑樣條的 GAM，說明相同加法結構可以換一維擬合方法作為組件（building block）。曲線相似不代表估計法相同。自然樣條控制基底維度，平滑樣條控制平滑懲罰；pyGAM 的 <code>gridsearch</code> 在它提供的候選規則下選平滑參數，與自行安排的外層效能評估仍是兩個步驟。</p>\n<h3>分類 GAM 為何在最低教育組不穩定？</h3>\n<p>分類改為 $\\operatorname{logit}p=\\beta_0+\\beta_1year+f_2(age)+f_3(education)$，目標是 <code>wage &gt; 250</code>。最低教育組沒有高薪事件時，該組係數可能朝負無窮移動，標準誤和 Wald 區間失去可靠性。講義移除該組後重擬合是示範分離的影響；因此結論只適用於留下的人群，不能把移除後的機率外推到被刪除的組。</p>\n<p>GAM 保留各變數的條件成分解讀，卻預設不同變數的形狀可相加。若年齡效果隨教育改變，單一 $f_2(age)$ 不足以表示；需明確加入交互作用或二維平滑項。增添項會增加複雜度，必須有足夠資料並重新驗證，而非把任何殘差結構都視為應增加平滑項。</p>\n')
    bodies['gam'] = extend(bodies['gam'], 'w08-detail-gam-thinplate', '\n<h3>四種效果圖如何回答不同問題？</h3>\n<p><strong>成分圖</strong>畫已擬合的 $\\hat f_j(x)$，條件是其他加法成分保持不變。<strong>偏殘差圖</strong>把 $e_i+\\hat f_j(x_{ij})$ 對 $x_{ij}$ 作圖：相當於先扣掉其他項再看該項的剩餘結構。點的散佈仍含雜訊與其他遺漏項，並不要求所有點落在曲線上。</p>\n<p><strong>部分迴歸圖</strong>適用於線性模型的指定欄位：先把 $y$ 對其他欄位迴歸取殘差，再把該 $x_j$ 對其他欄位迴歸取殘差，兩組殘差間的斜率等於原模型的係數。若一個樣條項有多個基底欄，不能把單一基底欄的斜率當成整個年齡曲線；這與偏殘差圖的縱軸和目的不同。</p>\n<p><strong>PDP</strong>每次固定目標特徵值，把其餘特徵依訓練樣本逐列帶入模型，再平均預測。加法迴歸中的 PDP 與成分曲線只差常數，但分類 GAM 的 logistic 轉換是非線性，平均機率不等於平均 logit 再轉換。年齡與教育高度相關時，替換年齡可能產生訓練資料中少見或未出現的組合；「控制其他變數」的圖形文字不構成因果識別。</p>\n<h3>OLS 殘差為何加總為零？</h3>\n<p>OLS 正常方程是 $B^T(y-B\\hat\\beta)=0$。若 $B$ 含常數欄，就得到 $\\sum_ie_i=0$；每個設計欄位也與樣本內殘差內積為零。這是同一訓練資料上的代數結果。沒有截距、帶懲罰、非線性估計或新資料殘差都不能原樣套用；即使內積為零，也不能推論殘差與年齡獨立或模型完全正確。</p>\n<p>薄板樣條用 $\\iint(g_{11}^2+2g_{12}^2+g_{22}^2)$ 衡量二維曲率，仿射平面是不受曲率懲罰的零空間。徑向基底以每個訓練點為中心，$r^2\\log r$ 與 $r^2\\log(r^2)$ 只差常數尺度，需連同係數或懲罰設定一致。配合附加的仿射正交限制，才能避免同一平面成分被重複表示。它提供二維交互作用的建模工具，不是把兩條單變數曲線直接相乘就完成的同一模型。</p>\n')
    sources = {('prologue', 'w08-detail-lecture-roadmap'): ['https://arxiv.org/pdf/2207.08815.pdf', 'https://arxiv.org/abs/2308.16898'], ('poly', 'w08-detail-poly-calculation'): ['https://islp.readthedocs.io/en/latest/datasets/Wage.html', 'https://stats.stackexchange.com/questions/136157/general-mathematics-for-confidence-interval-in-multiple-linear-regression', 'https://stats.stackexchange.com/questions/483362/pointwise-standard-errors-for-a-logistic-regression-fit-with-statsmodels'], ('natural', 'w08-detail-natural-basis'): ['https://stats.stackexchange.com/questions/233232/the-definition-of-natural-cubic-splines-for-regression', 'https://patsy.readthedocs.io/en/latest/spline-regression.html', 'https://stats.stackexchange.com/questions/490306/natural-splines-degrees-of-freedom?rq=1', 'https://www.hds.utc.fr/~tdenoeux/dokuwiki/_media/en/splines.pdf', 'https://math.stackexchange.com/questions/699113/what-is-the-relationship-between-cubic-b-splines-and-cubic-splines'], ('gam', 'w08-detail-gam-lab'): ['https://stats.stackexchange.com/questions/279576/partial-residuals-plot'], ('smooth', 'w08-detail-smoothing-computation'): ['https://github.com/empathy87/The-Elements-of-Statistical-Learning-Python-Notebooks/blob/master/examples/Bone Mineral Density.ipynb'], ('gam', 'w08-detail-gam-thinplate'): ['https://en.wikipedia.org/wiki/Partial_regression_plot', 'https://en.wikipedia.org/wiki/Partial_residual_plot', 'https://stats.stackexchange.com/questions/423375/why-is-there-residual-dots-in-plot-of-gam', 'https://stats.stackexchange.com/questions/189584/why-do-residuals-in-linear-regression-always-sum-to-zero-when-an-intercept-is-in', 'https://stats.stackexchange.com/questions/474102/why-is-the-correlation-between-independent-variables-regressor-and-residuals-zer', 'https://stats.stackexchange.com/questions/423375/why-is-there-residual-dots-in-plot-of-', 'https://stats.stackexchange.com/questions/189584/why-do-residuals-in-linear-regression-', 'https://stats.stackexchange.com/questions/474102/why-is-the-correlation-between-', 'https://christophm.github.io/interpretable-ml-book/pdp.html']}
    labels = {'arxiv.org/pdf/2207': '表格資料上的樹與深度學習比較', 'arxiv.org/abs/2308': '表格資料模型比較研究', 'Wage.html': 'Wage 資料說明', 'Hitters.html': 'Hitters 資料說明', '136157': '多元迴歸的平均反應區間', '483362': 'logistic 逐點標準誤', '233232': '自然樣條的邊界條件', '490306': '自然樣條的自由度', 'spline-regression.html': 'Patsy 樣條設計矩陣', 'Bone%20': 'Bone Mineral Density 平滑範例', 'Bone Mineral': 'Bone Mineral Density 平滑範例', 'splines.pdf': 'B-spline 教材', '699113': 'B-spline 與三次樣條', 'Partial_regression_plot': '部分迴歸圖', 'Partial_residual_plot': '偏殘差圖', '279576': '偏殘差的定義', '423375': 'GAM 圖中的殘差', '189584': '含截距 OLS 的殘差和', '474102': 'OLS 殘差與設計欄的正交性', 'pdp.html': 'PDP 的計算與限制', 'regression_tree.html': '迴歸樹的分裂推導', 'classification_tree.html': '分類樹的分裂推導', '45513511': '候選分裂門檻', '193538': '剪枝引數選擇', 'Heart.csv': 'Heart 資料下載', 'cat-to-numberic': 'CatBoost 有序類別統計', '4363939': '多數投票的二項機率', 'bagging.html': 'Bagging 原理', 'stat414': '相關平均量的變異', '709601': '分類器組合的理論來源', '978-3-642': '分類器組合教材', 'ESL_Solution': 'ESL 習題解答入口', 'random_forests.html': 'Random forest 去相關', 'extremely-randomized': 'Extra-trees 官方說明', 'boosting.html': '提升法推導', '3CC4': 'Gradient boosting 影片', 'step-by-step-gradient': 'Gradient boosting 逐步示範', '1603.02754': 'XGBoost 原論文', '353462': '樹模型與特徵尺度', 'catboost-vs-light': '三個 boosting 套件比較', 'tutorials/model': 'XGBoost 葉值與增益推導', 'ZVFe': 'XGBoost 概念影片', '202858': '二階 Taylor 近似', 'categorical.html': 'XGBoost 原生類別支援', 'faq.html': 'XGBoost 缺失值處理', 'oRrKe': 'XGBoost 搜尋與系統設計影片', 'QuantilesOverview': '分位數草圖原理', 'jboner': '記憶體存取延遲背景', 'Features.html': 'LightGBM 直方圖、GOSS 與 EFB', 'WangJengYun': '直方圖 boosting 補充', '26699': 'Leaf-wise 與 level-wise', '01621459': '類別排序分裂的統計來源', 'riskified': 'Boosting 套件選擇背景', '14491b': 'CatBoost 原論文', 'bootstrap-options': 'CatBoost MVS', 'neptune.ai': 'CatBoost 方法選擇背景', 'categorical_features_parameters': 'CatBoost 類別引數範例', 'dart.html': 'DART dropout 官方說明', 'tree-algorithms': '樹演演算法家族官方說明', 'ID3_algorithm': 'ID3 演演算法背景', 'Predictive_analytics': 'CART 背景', 'categorical-encoding': '類別編碼教學', 'target-encoding': 'K-fold target encoding', 'BART.pdf': 'BART 後驗更新教材', 'chefboost': 'ChefBoost 樹工具入口', 'xgboost.readthedocs.io/en/latest/': 'XGBoost 官方入口'}
    labels = {'arxiv.org/pdf/2207': '表格資料上的樹與深度學習比較', 'arxiv.org/abs/2308': '表格資料模型比較研究', 'Wage.html': 'Wage 資料說明', 'Hitters.html': 'Hitters 資料說明', '136157': '多元迴歸的平均反應區間', '483362': 'logistic 逐點標準誤', '233232': '自然樣條的邊界條件', '490306': '自然樣條的自由度', 'spline-regression.html': 'Patsy 樣條設計矩陣', 'Bone%20': 'Bone Mineral Density 平滑範例', 'Bone Mineral': 'Bone Mineral Density 平滑範例', 'splines.pdf': 'B-spline 教材', '699113': 'B-spline 與三次樣條', 'Partial_regression_plot': '部分迴歸圖', 'Partial_residual_plot': '偏殘差圖', '279576': '偏殘差的定義', '423375': 'GAM 圖中的殘差', '189584': '含截距 OLS 的殘差和', '474102': 'OLS 殘差與設計欄的正交性', 'pdp.html': 'PDP 的計算與限制', 'regression_tree.html': '迴歸樹的分裂推導', 'classification_tree.html': '分類樹的分裂推導', '45513511': '候選分裂門檻', '193538': '剪枝參數選擇', 'Heart.csv': 'Heart 資料下載', 'cat-to-numberic': 'CatBoost 有序類別統計', '4363939': '多數投票的二項機率', 'bagging.html': 'Bagging 原理', 'stat414': '相關平均量的變異', '709601': '分類器組合的理論來源', '978-3-642': '分類器組合教材', 'ESL_Solution': 'ESL 習題解答入口', 'random_forests.html': 'Random forest 去相關', 'extremely-randomized': 'Extra-trees 官方說明', 'boosting.html': '提升法推導', '3CC4': 'Gradient boosting 影片', 'step-by-step-gradient': 'Gradient boosting 逐步示範', '1603.02754': 'XGBoost 原論文', '353462': '樹模型與特徵尺度', 'catboost-vs-light': '三個 boosting 套件比較', 'tutorials/model': 'XGBoost 葉值與增益推導', 'ZVFe': 'XGBoost 概念影片', '202858': '二階 Taylor 近似', 'categorical.html': 'XGBoost 原生類別支援', 'faq.html': 'XGBoost 缺失值處理', 'oRrKe': 'XGBoost 搜尋與系統設計影片', 'QuantilesOverview': '分位數草圖原理', 'jboner': '記憶體存取延遲背景', 'Features.html': 'LightGBM 直方圖、GOSS 與 EFB', 'WangJengYun': '直方圖 boosting 補充', '26699': 'Leaf-wise 與 level-wise', '01621459': '類別排序分裂的統計來源', 'riskified': 'Boosting 套件選擇背景', '14491b': 'CatBoost 原論文', 'bootstrap-options': 'CatBoost MVS', 'neptune.ai': 'CatBoost 方法選擇背景', 'categorical_features_parameters': 'CatBoost 類別參數範例', 'dart.html': 'DART dropout 官方說明', 'tree-algorithms': '樹演算法家族官方說明', 'ID3_algorithm': 'ID3 演算法背景', 'Predictive_analytics': 'CART 背景', 'categorical-encoding': '類別編碼教學', 'target-encoding': 'K-fold target encoding', 'BART.pdf': 'BART 後驗更新教材', 'chefboost': 'ChefBoost 樹工具入口', 'xgboost.readthedocs.io/en/latest/': 'XGBoost 官方入口'}
    for (section, pid), urls in sources.items():
        entries = "、".join('<a href="'+escape(u,quote=True)+'" target="_blank" rel="noopener">'+escape(next((name for key,name in labels.items() if key in u),u.split('/')[2]))+'</a>' for i,u in enumerate(urls))
        bodies[section] = extend(bodies[section], pid, '<p class="source-links">本主題的講義來源與延伸閱讀：'+entries+'。</p>')
    return bodies
