const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'../../../..'),out=path.join(root,'tools/verification/course-alignment-20260908/visual-review');
const puppeteer=require(path.join(process.env.HOME,'.cache/selfstudy-node/node_modules/puppeteer-core'));
const base=path.join(process.env.HOME,'.cache/puppeteer/chrome'),chrome=path.join(base,fs.readdirSync(base).sort().at(-1),'chrome-linux64/chrome');
(async()=>{const browser=await puppeteer.launch({executablePath:chrome,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});const page=await browser.newPage();await page.setViewport({width:1280,height:900});await page.goto('file://'+path.join(root,'introduction.html'),{waitUntil:'networkidle0'});
for(const id of ['w01ivWageAge','w01ivWageYear','w01ivWageEdu','w01ivSmarketBox','w01ivSmarketCorr','w01ivNci','w01ivNci3','w01ivAutoHist','w01ivAutoJoint','w01ivAutoPairs','w01ivBikeMonth','w01ivBike']){const el=await page.$('#'+id);await el.screenshot({path:path.join(out,id+'.png')});console.log('captured',id);}
console.log(JSON.stringify(await page.evaluate(()=>({nciPoints:document.querySelectorAll('#w01ivNci .w01iv-nci-point').length,nci3Points:document.querySelectorAll('#w01ivNci3 .w01iv-nci-point').length,legend:[...new Set(FRAMES_w01nci.pts.map(p=>p.g))],wagePoints:document.querySelectorAll('#w01ivWageAge .w01iv-point').length,pairDots:document.querySelectorAll('#w01ivAutoPairs circle').length,pairDensities:document.querySelectorAll('#w01ivAutoPairs polygon').length})),null,2));
const bands=await page.$$eval('.w01iv-band',els=>els.map(el=>({tag:el.tagName,fill:getComputedStyle(el).fill,opacity:getComputedStyle(el).fillOpacity,points:el.getAttribute('points').split(' ').length}))); console.log('Wage bands',JSON.stringify(bands)); if(bands.length!==2 || bands.some(b=>b.tag!=='polygon'||b.fill==='none'))throw Error('Wage confidence band is not visibly filled');
await page.setViewport({width:390,height:844});const scroll=await page.$('#w01ivAutoPairs');console.log('mobile scroll',await scroll.evaluate(el=>{const p=el.parentElement;const before=p.scrollLeft;p.scrollLeft=p.scrollWidth;return {before,after:p.scrollLeft,clientWidth:p.clientWidth,scrollWidth:p.scrollWidth,overflow:getComputedStyle(p).overflowX,bodyOverflow:document.documentElement.scrollWidth-document.documentElement.clientWidth};})); await (await page.$('#w01ivAutoPairs')).screenshot({path:path.join(out,'auto-pairs-mobile.png')});
await page.goto('file://'+path.join(root,'00b_setup.html'),{waitUntil:'networkidle0'});console.log('setup counters',await page.$$eval('[id^=w13clN]',els=>els.length));await page.evaluate(()=>w13clTopDown());console.log('setup sequential',await page.$eval('#w13clStatus',el=>el.innerText));await (await page.$('#w13clStatus')).screenshot({path:path.join(out,'setup-sequence.png')});await browser.close();})();
